# name = input("Введите ваше имя: ")
# print("Здравствуйте," , name)
# current_year = 2024
# date_of_birth = int(input("В каком году вы родились? "))
# age = (current_year - date_of_birth)
# print("В этом году Вам",age, "лет")
# print("привет,я строка в нижнем регистре" .upper().lower())
my_string=input ("Введите название компании: ")
print(len(my_string ))
print("my_string".upper())
print("my_string".lower())
print("my_string" .replace("_", ""))
print("my_string" .replace("y_string", ""))
print("my_string" .replace("my_strin", ""))